# Docu of all options: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseurl = "https://blog.weltraumschaf.de/"
languageCode = "en_US"
title = "Das Weltraumschaf"
theme = "hugo-tikva"
enforce_ssl = true
# Exclude pages with draft status of true
builddrafts = false
# Turns relative urls into absolute urls
canonifyurls = true
disablePathToLower = true
# https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# Language setting of the site, for language configuration see
#  https://gohugo.io/content-management/multilingual/
# There are only a few strings which need to be translated, feel free to add more
# languages.
DefaultContentLanguage = "en"

# Intresting themes:
# https://github.com/cntrump/hugo-notepadium
# https://github.com/keichi/vienna
# https://github.com/gyorb/hugo-dusk
# https://github.com/salcan/BeyondNothing

[params]
    # Theme https://github.com/geschke/hugo-tikva
    subtitle = "IT-Security — Software Architecture — Clean Code"
    favicon = '/img/favicon.ico'
    showDate = true
    showNumberOfWords = true

[params.theme]
#bootstrapTheme = 'bolt'
#bootstrapTheme = 'bstrap'
#bootstrapTheme = 'btcn'
#bootstrapTheme = 'calabaza'
#bootstrapTheme = 'cerulean'
# fav: strand
bootstrapTheme = 'cosmo'
# bootstrapTheme = 'cyborg'
# fav:
# bootstrapTheme = 'darkly'
# fav: strand
# bootstrapTheme = 'flatly'
# fav: strand
# bootstrapTheme = 'hoff'
# bootstrapTheme = 'journal'
# fav: strand
# bootstrapTheme = 'kdo_flatly'
# bootstrapTheme = 'kdo2'
# fav: strand
# bootstrapTheme = 'kunsch'
# bootstrapTheme = 'lumen'
# Coole typo:
# bootstrapTheme = 'lux'
# bootstrapTheme = 'malibu'
# bootstrapTheme = 'materia'
# bootstrapTheme = 'minim'
# fav: strand
# bootstrapTheme = 'minty'
# fav: strand
# bootstrapTheme = 'pulse'
# fav: strand
# bootstrapTheme = 'signa'
# bootstrapTheme = 'simplex'
# bootstrapTheme = 'sketchy'
# fav:
# bootstrapTheme = 'slate_accessibility_ready'
# bootstrapTheme = 'slate'
# fav:
# bootstrapTheme = 'solar'
# bootstrapTheme = 'sonic'
# bootstrapTheme = 'spacelab'
# bootstrapTheme = 'united'
# bootstrapTheme = 'yeti'

# [params.navbar]
#     colorScheme = "navbar-light"

[params.theme.header]
    image = '/img/header_strand.jpg'
    width = 940
    height = 200
    # image = '/img/header_shuttle_cockpit.jpg'
    # width = 1500
    # height = 500
    displayHeaderText = true

[menu]

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/blog/"
    weight = 20

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

[[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"
    weight = 60

# [[params.social]]
# url  = "http://weltraumschaf.github.io/"
# icon = "github"

# [[params.social]]
# url  = "https://twitter.com/Weltraumschaf"
# icon = "twitter"

# [[params.social]]
# url  = "https://dev.to/weltraumschaf"
# icon = "laptop"

# [[params.social]]
# url  = "https://stackoverflow.com/users/952722/weltraumschaf"
# icon = "stack-overflow"

# [[params.social]]
# url  = "https://www.xing.com/profile/Sven_Strittmatter"
# icon = "xing"

# [[params.social]]
# url  = "https://de.linkedin.com/in/sven-strittmatter-53775121"
# icon = "linkedin"

# [[params.social]]
# url  = "https://soundcloud.com/weltraumschaf"
# icon = "soundcloud"
