# Docu of all options: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://blog.weltraumschaf.de/"
languageCode = "en_US"
title = "Das Weltraumschaf"
theme = "hugo-notepadium"
copyright = "© 2020 Sven Strittmatter"
enforce_ssl = true
# Exclude pages with draft status of true
builddrafts = false
# Turns relative urls into absolute urls
canonifyurls = true
disablePathToLower = true
# https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# Language setting of the site, for language configuration see
#  https://gohugo.io/content-management/multilingual/
# There are only a few strings which need to be translated, feel free to add more
# languages.
defaultContentLanguage = "en"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "dark"
dateFormat = " 2. January 2020"
logo = "/img/ich.jpg"
slogan = "Security / Software Architecture / Clean Code"
fullRss = true

[params.nav]
showCategories = false
showTags = false

[[params.nav.custom]]
title = "Projects"
url = "/projects/"

[[params.nav.custom]]
title = "About me"
url = "/about/"

[[params.nav.custom]]
title = "Contact"
url = "/contact/"

[[params.nav.custom]]
title = "Impressum"
url = "/impressum/"